# Generated by Django 6.0.2 on 2026-02-25 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qahistory',
            name='related_docs',
            field=models.TextField(blank=True, null=True),
        ),
    ]
