# Generated by Django 6.0.2 on 2026-02-25 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_qahistory_related_docs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qahistory',
            name='related_docs',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
